# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UFT_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 600)
        Form.setMinimumSize(QtCore.QSize(0, 550))
        self.title_label = QtWidgets.QLabel(Form)
        self.title_label.setGeometry(QtCore.QRect(9, 9, 261, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAutoFillBackground(False)
        self.title_label.setTextFormat(QtCore.Qt.AutoText)
        self.title_label.setObjectName("title_label")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(9, 145, 1061, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.info = QtWidgets.QWidget()
        self.info.setObjectName("info")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.info)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.info_textBrowser = QtWidgets.QTextBrowser(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_textBrowser.sizePolicy().hasHeightForWidth())
        self.info_textBrowser.setSizePolicy(sizePolicy)
        self.info_textBrowser.setAutoFillBackground(True)
        self.info_textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.info_textBrowser.setObjectName("info_textBrowser")
        self.gridLayout_8.addWidget(self.info_textBrowser, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.info, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.search_lineEdit.setInputMask("")
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.horizontalLayout_2.addWidget(self.search_lineEdit)
        self.search_pushButton = QtWidgets.QPushButton(self.tab)
        self.search_pushButton.setObjectName("search_pushButton")
        self.horizontalLayout_2.addWidget(self.search_pushButton)
        self.search_result_label = QtWidgets.QLabel(self.tab)
        self.search_result_label.setText("")
        self.search_result_label.setObjectName("search_result_label")
        self.horizontalLayout_2.addWidget(self.search_result_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.log_tableView = QtWidgets.QTableView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_tableView.sizePolicy().hasHeightForWidth())
        self.log_tableView.setSizePolicy(sizePolicy)
        self.log_tableView.setMinimumSize(QtCore.QSize(994, 0))
        self.log_tableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.log_tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.log_tableView.setObjectName("log_tableView")
        self.gridLayout_5.addWidget(self.log_tableView, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 1061, 97))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_1 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_1.sizePolicy().hasHeightForWidth())
        self.groupBox_1.setSizePolicy(sizePolicy)
        self.groupBox_1.setObjectName("groupBox_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sn_lineEdit_1 = QtWidgets.QLineEdit(self.groupBox_1)
        self.sn_lineEdit_1.setAcceptDrops(True)
        self.sn_lineEdit_1.setText("")
        self.sn_lineEdit_1.setMaxLength(33)
        self.sn_lineEdit_1.setObjectName("sn_lineEdit_1")
        self.verticalLayout.addWidget(self.sn_lineEdit_1)
        self.label_1 = QtWidgets.QLabel(self.groupBox_1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.horizontalLayout.addWidget(self.groupBox_1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sn_lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.sn_lineEdit_2.setMaxLength(33)
        self.sn_lineEdit_2.setObjectName("sn_lineEdit_2")
        self.verticalLayout_9.addWidget(self.sn_lineEdit_2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.sn_lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.sn_lineEdit_3.setMaxLength(33)
        self.sn_lineEdit_3.setObjectName("sn_lineEdit_3")
        self.verticalLayout_8.addWidget(self.sn_lineEdit_3)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sn_lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.sn_lineEdit_4.setMaxLength(33)
        self.sn_lineEdit_4.setObjectName("sn_lineEdit_4")
        self.verticalLayout_7.addWidget(self.sn_lineEdit_4)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.start_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_pushButton.sizePolicy().hasHeightForWidth())
        self.start_pushButton.setSizePolicy(sizePolicy)
        self.start_pushButton.setObjectName("start_pushButton")
        self.horizontalLayout.addWidget(self.start_pushButton)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 560, 1061, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_4.addWidget(self.lcdNumber)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.sn_lineEdit_1.returnPressed.connect(self.sn_lineEdit_2.setFocus)
        self.sn_lineEdit_2.returnPressed.connect(self.sn_lineEdit_3.setFocus)
        self.sn_lineEdit_3.returnPressed.connect(self.sn_lineEdit_4.setFocus)
        self.sn_lineEdit_1.returnPressed.connect(self.sn_lineEdit_2.clear)
        self.sn_lineEdit_2.returnPressed.connect(self.sn_lineEdit_3.clear)
        self.sn_lineEdit_3.returnPressed.connect(self.sn_lineEdit_4.clear)
        self.start_pushButton.clicked.connect(self.info_textBrowser.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AGIGA-UFT-TEST"))
        self.title_label.setText(_translate("Form", "AGIGA PGEM UFT TOPAZ V2.30"))
        self.groupBox_6.setTitle(_translate("Form", "info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.info), _translate("Form", "test"))
        self.search_lineEdit.setPlaceholderText(_translate("Form", "search by serial number"))
        self.search_pushButton.setText(_translate("Form", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "test log"))
        self.groupBox_1.setTitle(_translate("Form", "Board #1"))
        self.sn_lineEdit_1.setPlaceholderText(_translate("Form", "Serial Number"))
        self.groupBox_2.setTitle(_translate("Form", "Board #2"))
        self.sn_lineEdit_2.setPlaceholderText(_translate("Form", "Serial Number"))
        self.groupBox_3.setTitle(_translate("Form", "Board #3"))
        self.sn_lineEdit_3.setPlaceholderText(_translate("Form", "Serial Number"))
        self.groupBox_4.setTitle(_translate("Form", "Board #4"))
        self.sn_lineEdit_4.setPlaceholderText(_translate("Form", "Serial Number"))
        self.start_pushButton.setText(_translate("Form", "START"))

